format = """
$directory\
$git_branch"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style) "

[git_branch]
symbol = "âŽ‡ "
style = "bold purple"
format = "on [$symbol$branch]($style)"
